resources:
  - name: Git_Repo1
    type: GitRepo
    configuration:
      path: bindushree16/test
      gitProvider: bindu_github
      branches: 
        include: master
      files:  
        include: pipelines.yml

pipelines:
  - name: test_pipeline
    steps:
      - name: my_SteptestReports
        type: Bash
        configuration: 
          nodePool: bindu_u16azure
        execution:
          onExecute:
            - echo "hi"
