resources:
  - name: Git_Repo1
    type: GitRepo
    configuration:
      path: bindushree16/test
      gitProvider: bindu_github
      branches: 
        include: master
#       files:  
#         include: pipelines.yml

pipelines:
  - name: test_pipeline
    steps:
      - name: my_SteptestReports
        type: Bash
        configuration: 
          environmentVariables: 
            env1: value1
#         configuration: 
#           nodePool: testing_node
        execution:
          onExecute:
            - echo "hi"
